# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confidence_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("background-color: rgb(117, 249, 244);\n"
"font-family: Noto Sans SC;")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.confidence_lbl = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Noto Sans SC")
        font.setBold(True)
        font.setWeight(75)
        self.confidence_lbl.setFont(font)
        self.confidence_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.confidence_lbl.setObjectName("confidence_lbl")
        self.verticalLayout.addWidget(self.confidence_lbl)
        self.value_confidence_line = QtWidgets.QLineEdit(Dialog)
        self.value_confidence_line.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.value_confidence_line.setObjectName("value_confidence_line")
        self.verticalLayout.addWidget(self.value_confidence_line)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 0, 0, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.confidence_lbl.setText(_translate("Dialog", "Значение доверительной вероятности"))
        self.save_btn.setText(_translate("Dialog", "Задать"))
        self.cancel_btn.setText(_translate("Dialog", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
