# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(117, 249, 244);\n"
"font-family: Noto Sans SC;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clear_btn.setIcon(icon)
        self.clear_btn.setIconSize(QtCore.QSize(25, 40))
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout_2.addWidget(self.clear_btn)
        self.confidence_probability_btn = QtWidgets.QPushButton(self.centralwidget)
        self.confidence_probability_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/confidence.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confidence_probability_btn.setIcon(icon1)
        self.confidence_probability_btn.setIconSize(QtCore.QSize(40, 40))
        self.confidence_probability_btn.setObjectName("confidence_probability_btn")
        self.horizontalLayout_2.addWidget(self.confidence_probability_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.uncertainty_table = QtWidgets.QTableWidget(self.centralwidget)
        self.uncertainty_table.setStyleSheet("")
        self.uncertainty_table.setObjectName("uncertainty_table")
        self.uncertainty_table.setColumnCount(0)
        self.uncertainty_table.setRowCount(0)
        self.verticalLayout.addWidget(self.uncertainty_table)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.uncerteinty_typeb_btn = QtWidgets.QPushButton(self.centralwidget)
        self.uncerteinty_typeb_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/uncertainty.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uncerteinty_typeb_btn.setIcon(icon2)
        self.uncerteinty_typeb_btn.setIconSize(QtCore.QSize(40, 40))
        self.uncerteinty_typeb_btn.setObjectName("uncerteinty_typeb_btn")
        self.horizontalLayout.addWidget(self.uncerteinty_typeb_btn)
        self.add_value = QtWidgets.QPushButton(self.centralwidget)
        self.add_value.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_value.setIcon(icon3)
        self.add_value.setIconSize(QtCore.QSize(30, 30))
        self.add_value.setObjectName("add_value")
        self.horizontalLayout.addWidget(self.add_value)
        self.save_btn = QtWidgets.QPushButton(self.centralwidget)
        self.save_btn.setStyleSheet("QPushButton {\n"
"background-color: rgba(255,255,255,30);\n"
"border: 2px solid rgba(255,255,255,40);\n"
"border-radius: 10px;\n"
"font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"}\n"
"QPushButton::hover {\n"
"background-color: rgba(255,255,255,50);\n"
"}\n"
"QPushButton::pressed {\n"
"background-color: rgba(255,255,255,80);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon4)
        self.save_btn.setIconSize(QtCore.QSize(40, 30))
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout.addWidget(self.save_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.clear_btn.setText(_translate("MainWindow", "Очистить таблицу"))
        self.confidence_probability_btn.setText(_translate("MainWindow", "Задать доверительную вероятность"))
        self.uncerteinty_typeb_btn.setText(_translate("MainWindow", "Задать неопределённость типа B"))
        self.add_value.setText(_translate("MainWindow", "Добавить значение"))
        self.save_btn.setText(_translate("MainWindow", "Сохранить"))
import res_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
